
karyotype = karyotype.txt

chromosomes_order_by_karyotype = yes
chromosomes_units              = 1000000
chromosomes_display_default    = yes

chromosomes         = nn1;nn2;nn3;nn4;nn5;nn6;nn7;nn8;nn9;nn10;nn11;nn12;nn13;nn14;nn15;nn16;nn17;nn18;nn19;nn20;nn21;nn22;nn23;nn24;nn25;nn26;nn27;nn28;nn29;nn30;nn31;nn32;nn33;nn34;nn35;nn36;nn37;nn38;nn39;nn40;nnW;nnZ
chromosomes_color    = /hg/=blues-5-seq-4
